# .github/workflows/deploy.yml
name: Deploy Application

on:
  push:
    branches:
      - main  # main 브랜치에 변경 사항이 있을 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Node.js 버전을 지정

      - name: Install dependencies
        run: npm install

      - name: Run application with API key
        env:
          API_KEY: ${{ secrets.API_KEY }}  # GitHub Secrets에서 API 키 가져오기
        run: |
          echo "Using API Key"
          node your_script.js  # 실제 API 키가 필요한 스크립트를 실행
